version: '3'
services: 
  
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network
    volumes:
      - mariadb-data:/var/lib/mysql
  
 
  fbbservice:
    image: fbb_app:v1
    networks:
      - internal-container-network
    ports:
      - 8103:80
    depends_on:
      - db
  
 
  

volumes:
 mariadb-data:
 sqldata:
networks:
 internal-container-network:
  driver: bridge
